<Project Sdk="Microsoft.NET.Sdk">
  
  <ItemGroup>
    <ProjectReference Include="..\OnTime.Domain\OnTime.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="Hangfire.Core" />
    <PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>

</Project>
