services:
  postgres:
    image: postgres:18-alpine
    container_name: ontime-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ontime
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql

  mailpit:
    image: axllent/mailpit:v1.30
    container_name: ontime-mailpit
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"

  cdn:
    image: nginx:1.31-alpine
    container_name: ontime-cdn
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ../infra/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../backend/images/optimized:/usr/share/nginx/html/images:ro
    
  keycloak:
    image: quay.io/keycloak/keycloak:26.7.0
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info
    volumes:
      - ./containers/keycloak:/opt/keycloak/data
    ports:
      - "5000:8080"
    command: [ "start-dev" ]

volumes:
  postgres-data:
